# Generated by Django 6.0.6 on 2026-06-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('run_bot', 'Can run bot'), ('stop_bot', 'Can stop bot'), ('view_logs', 'Can view logs'), ('run_workflow', 'Can run workflow'), ('edit_workflow', 'Can edit workflow'), ('delete_workflow', 'Can delete workflow'), ('manage_users', 'Can manage users')],
            },
        ),
    ]
