# Generated by Django 6.0.6 on 2026-06-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='name',
            field=models.CharField(default='permission', max_length=10),
        ),
    ]
