# Generated by Django 6.0.6 on 2026-06-21 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rolepermission_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'permissions': [('create_bot', 'Can create bot'), ('view_bot', 'Can view bot'), ('edit_bot', 'Can edit bot'), ('delete_bot', 'Can delete bot'), ('run_bot', 'Can run bot'), ('stop_bot', 'Can stop bot'), ('create_workflow', 'Can create workflow'), ('view_workflow', 'Can view workflow'), ('edit_workflow', 'Can edit workflow'), ('delete_workflow', 'Can delete workflow'), ('run_workflow', 'Can run workflow'), ('view_logs', 'Can view logs'), ('manage_users', 'Can manage users')]},
        ),
    ]
